FactoryGirl.create_list( :client, 20 )
FactoryGirl.create_list( :jornal, 10 )
FactoryGirl.create_list( :diario_oficial, 10 )
FactoryGirl.create_list( :material, 10 )
FactoryGirl.create_list( :segment, 5 )
FactoryGirl.create_list( :retranca, 40 )
FactoryGirl.create_list( :publicacao, 10 )
